version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-cliente-db
    environment:
      POSTGRES_DB: clienteservicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reforma2
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cuenta-service:
    build: .
    container_name: cliente-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clienteservicesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: reforma2
    depends_on:
      postgres:
        condition: service_healthy